### ISSUE TITLE
Email verification error

### ISSUE THREAD

**Issue by asimakos** [cfwheels/cfwheels-example-app#11]
After successful installation of this great app, i tried to create my first user. Email verification is compulsory, otherwise account is in pending condition. Since i do not receive any email from this app for account verification, is there any way to bypass it and login successfully into this app?

Regards

**Comment by 18thAvenue** [comment]
Go to the users table in the database and set the field 'verified' to 1 for that user.

**Comment by asimakos** [comment]
Thanks for the information! I would like to play with the admin user or other privileged users besides simple ones. Is it possible and how to create an admin user, since i do not have many possibilities of this great app via simple users only?

Regards

**Comment by neokoenig** [comment]
There are several default users. Please read the wiki:
Specifically:
https://github.com/cfwheels/cfwheels-example-app/wiki/Emails
https://github.com/cfwheels/cfwheels-example-app/wiki/Logging-in
