### ISSUE TITLE
Hi, I got error. application.encryotionKey in /config/onpplicationstart.cfm

### ISSUE THREAD

**Issue by jimmyham** [cfwheels/cfwheels-example-app#12]
Hi, I got error. application.encryotionKey in /config/onpplicationstart.cfm
I change with like this.

is it correct?

// Still, use generateSecretKey("AES") to generate a new one.
		//application.encryptionKey = "7NNEID99l07DySzq1LJnEA==";
		application.encryptionKey = generateSecretKey("AES");
		createApplicationSettings();

**Comment by neokoenig** [comment]
Not quite. That function generates a new key each time it's called, so you just need to run it once and then add the result; i.e, on https://trycf.com/ - run this:
```
writeDump(generateSecretKey("AES"));
```
And use the resulting string.

**Comment by jimmyham** [comment]
Thank you, I reinstalled. It's cleared.
