### ISSUE TITLE
key [LANG] doesn't exist in the request scope

### ISSUE THREAD

**Issue by jimmyham** [cfwheels/cfwheels-example-app#13]
Hi, I got error. After login with admin

in DefaultLanguage Setting. >  Edit 

Url: http://127.0.0.1:60050/admin/settings/20/edit

Message: key [LANG] doesn't exist in the request scope
--
Stacktrace | The Error Occurred in/wheels../views/admin/settings/_form.cfm: line 19

I dumped setting.options
like this <cfdump var="#setting.options#">

String: [[request.lang.availablelanguages]]

Where can I fix it and how?

Thank you.

**Comment by neokoenig** [comment]
Yeah, sorry, I intended to localise this for multi language, but it was too much work to start with - those settings won't really do anything.

**Comment by jimmyham** [comment]
ok. I see.
