### ISSUE TITLE
key [LANG] doesn't exist in the request scope

### ISSUE THREAD

**Issue by MvdO** [cfwheels/cfwheels-example-app#5]
Using this URL: http://127.0.0.1:60050/admin/settings/8/edit

Getting error:  key [LANG] doesn't exist in the request scope

![image](https://user-images.githubusercontent.com/14022664/41815379-58dd28d6-7769-11e8-8688-76533bea3547.png)

**Comment by neokoenig** [comment]
I've actually removed these already in the current master, so already fixed.
The i8n options were just there from the code I based it off.

I would like to add full localisation/i8n, but need to have a think about
the best way to make it maintainable.

**Comment by MvdO** [comment]
Ok thanks, let me know if I can help in any way.
